from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('about/', views.about, name='about'),
    path('solutions/', views.solutions, name='solutions'),
    path('how-it-works/', views.how_it_works, name='how-it-works'),
    path('impact/', views.impact, name='impact'),
    path('team/', views.team, name='team'),
    path('careers/', views.careers, name='careers'),
    path('get-quote/', views.get_quote, name='get-quote'),
    path('partners/', views.partners, name='partners'),
    path('investors/', views.investors, name='investors'),
    path('contact/', views.contact, name='contact'),
    path('careers/apply/', views.careers_apply, name='careers-apply'),
    path('newsletter/subscribe/', views.newsletter_subscribe, name='newsletter-subscribe'),
    path('logout/', views.logout_view, name='logout'),
    path('payments/', views.payments_list, name='payments_list'),
    path('payments/<int:payment_id>/', views.payment_detail, name='payment_detail'),
    path('api/device-data/<str:device_sn>/', views.device_data, name='device-data'),
    path('api/station-energy/<str:station_id>/', views.station_energy, name='station-energy'),
    path('api/filtered-data/<str:station_id>/', views.filtered_data, name='filtered-data'),
    path('api/device-tou/<str:device_sn>/', views.device_tou, name='device-tou'),
    path('api/create-incident/', views.create_incident, name='create-incident'),
    path('api/mark-notification-read/<int:notification_id>/', views.mark_notification_read, name='mark-notification-read'),
    path('api/alerts/', views.api_alerts, name='api-alerts'),
    path('api/notifications/', views.api_notifications, name='api-notifications'),
    path('api/admin/alerts/', views.api_admin_alerts, name='api-admin-alerts'),
    path('api/update-profile/', views.update_profile, name='update-profile'),
    
    # Wallet URLs
    path('wallet/', views.wallet_dashboard, name='wallet-dashboard'),
    path('wallet/transaction/<int:transaction_id>/', views.wallet_transaction_detail, name='wallet-transaction-detail'),
    path('wallet/top-up/', views.wallet_top_up, name='wallet-top-up'),
    path('wallet/transfer/', views.wallet_transfer, name='wallet-transfer'),
    path('wallet/confirmation/<int:transaction_id>/', views.wallet_confirmation, name='wallet-confirmation'),
    
    # Admin URLs
    path('admin-dashboard/', views.admin_dashboard, name='admin-dashboard'),
    path('api/admin/dashboard-data/', views.admin_dashboard_data, name='admin-dashboard-data'),
    path('admin/applications/', views.admin_applications, name='admin-applications'),
    path('admin/applications/update/<str:reference>/', views.admin_application_update, name='admin-application-update'),
    path('admin/customers/', views.admin_customers, name='admin-customers'),
    path('admin/customers/update/<str:customer_id>/', views.admin_customer_update, name='admin-customer-update'),
    path('admin/customers/print/<int:customer_id>/', views.admin_customer_print, name='admin-customer-print'),
    path('admin/customers/download-pdf/<int:customer_id>/', views.admin_customer_download_pdf, name='admin-customer-download-pdf'),
    path('admin/customers/print-all/', views.admin_customers_print_all, name='admin-customers-print-all'),
    path('admin/sites/', views.admin_sites, name='admin-sites'),
    path('admin/sites/new/', views.admin_site_new, name='admin-site-new'),
    path('admin/system-setup/', views.admin_system_setup, name='admin-system-setup'),
    path('admin/system-setup/new/', views.admin_system_setup_new, name='admin-system-setup-new'),
    path('admin/system-setup/edit/<int:site_id>/', views.admin_system_setup_edit, name='admin-system-setup-edit'),
    path('admin/system-setup/preview/<int:site_id>/', views.admin_system_setup_preview, name='admin-system-setup-preview'),
    path('admin/system-setup/delete/<int:site_id>/', views.admin_system_setup_delete, name='admin-system-setup-delete'),
    path('admin/system-setup/images/<int:site_id>/', views.admin_system_setup_images, name='admin-system-setup-images'),
    path('admin/billings/', views.admin_billings, name='admin-billings'),
    path('admin/billings/update/<str:reference>/', views.admin_billing_update, name='admin-billing-update'),
    path('admin/payments/', views.admin_payments, name='admin-payments'),
    path('admin/payments/update/<str:reference>/', views.admin_payment_update, name='admin-payment-update'),
    path('admin/partner-invoices/', views.admin_partner_invoices, name='admin-partner-invoices'),
    path('admin/partner-invoices/update/<str:reference>/', views.admin_partner_invoice_update, name='admin-partner-invoice-update'),
    path('admin/rfqs/', views.admin_rfqs, name='admin-rfqs'),
    path('admin/rfqs/update/<str:reference>/', views.admin_rfq_update, name='admin-rfq-update'),
    path('admin/dispatches/', views.admin_dispatches, name='admin-dispatches'),
    path('admin/dispatches/update/<str:reference>/', views.admin_dispatch_update, name='admin-dispatch-update'),
    path('admin/wallet/', views.admin_wallet, name='admin-wallet'),
    path('admin/team/', views.admin_team, name='admin-team'),
    path('admin/team/update/<str:email>/', views.admin_team_update, name='admin-team-update'),
    path('admin/team/edit/<str:email>/', views.admin_team_edit, name='admin-team-edit'),
    path('admin/team/print/', views.admin_team_print, name='admin-team-print'),
    path('admin/team/new/', views.admin_team_new, name='admin-team-new'),
    path('admin/notifications/', views.admin_notifications, name='admin-notifications'),
    path('admin/notifications/update/<str:id>/', views.admin_notification_update, name='admin-notification-update'),
    path('admin/notifications/new/', views.admin_notification_new, name='admin-notification-new'),
    path('admin/incidents/', views.admin_incidents, name='admin-incidents'),
    path('admin/incidents/update/<str:id>/', views.admin_incident_update, name='admin-incident-update'),
    path('admin/incidents/new/', views.admin_incident_new, name='admin-incident-new'),
    path('admin/alerts/', views.admin_alerts, name='admin-alerts'),
    path('admin/alerts/update/<str:id>/', views.admin_alert_update, name='admin-alert-update'),
    
    # Team registration onboarding
    path('team/create-login/<int:user_id>/<str:otp_code>/<str:role>/', views.team_create_login, name='team-create-login'),
    path('team/verify-otp/<int:user_id>/', views.team_verify_otp, name='team-verify-otp'),
    
    # Registration API endpoints
    path('api/send-phone-otp/', views.SendPhoneOtpView.as_view(), name='send-phone-otp'),
    path('api/verify-phone-otp/', views.VerifyPhoneOtpView.as_view(), name='verify-phone-otp'),
    path('api/complete-registration/', views.CompleteRegistrationView.as_view(), name='complete-registration'),
    path('api/verify-email-otp/', views.VerifyEmailOtpView.as_view(), name='verify-email-otp'),
    path('api/resend-email-otp/', views.ResendEmailOtpView.as_view(), name='resend-email-otp'),
    path('api/complete-other-details/', views.CompleteOtherDetailsView.as_view(), name='complete-other-details'),
    
    # Login API endpoints
    path('api/send-login-otp/', views.SendLoginOtpView.as_view(), name='send-login-otp'),
    path('api/verify-login-otp/', views.VerifyLoginOtpView.as_view(), name='verify-login-otp'),
]
