# Generated by Django 4.2.28 on 2026-02-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0003_customer_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_type', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('mpesa_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_time', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vegrid_app.customer')),
            ],
        ),
    ]
