# Generated by Django 4.2.28 on 2026-02-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0005_wallet_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeyeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Solar Site', max_length=100)),
                ('device_sn', models.CharField(max_length=100, unique=True)),
                ('deye_username', models.CharField(blank=True, max_length=100, null=True)),
                ('deye_password', models.CharField(blank=True, max_length=100, null=True)),
                ('last_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deye_devices', to='vegrid_app.customer')),
            ],
        ),
    ]
