# Generated by Django 4.2.28 on 2026-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0008_notification_customerbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbilling',
            name='billing_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
