# Generated by Django 4.2.28 on 2026-02-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0009_customerbilling_billing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('all', 'All Customers'), ('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(default='VEGRID ADMIN', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vegrid_app.customer'),
        ),
    ]
