# Generated by Django 4.2.28 on 2026-02-28 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vegrid_app', '0012_billingupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='vegrid_app.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
