# Generated by Django 4.2.28 on 2026-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0020_deyedevice_area_deyedevice_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyedevice',
            name='load',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
