# Generated by Django 4.2.28 on 2026-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0021_deyedevice_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyedevice',
            name='town',
            field=models.CharField(default='Nairobi', max_length=100),
        ),
    ]
