# Generated by Django 4.2.28 on 2026-03-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0022_deyedevice_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
