# Generated by Django 4.2.28 on 2026-03-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0023_alter_alert_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
