# Generated by Django 4.2.28 on 2026-03-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0026_customer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyedevice',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
    ]
