# Generated by Django 4.2.28 on 2026-03-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0027_deyedevice_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Customer ID'),
        ),
    ]
