# Generated by Django 4.2.28 on 2026-03-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0029_deyedevice_latitude_deyedevice_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyedevice',
            name='today_consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='total_consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
