# Generated by Django 4.2.28 on 2026-03-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0031_deyedevice_today_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyedevice',
            name='battery_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='battery_capacity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='currency',
            field=models.CharField(default='KES', max_length=20),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='installation_engineer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='installed_capacity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='installer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='inverter_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='inverter_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='owner',
            field=models.CharField(default='AwaGrid', max_length=100),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='service_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='service_rep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deyedevice',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.CreateModel(
            name='DeyeDeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vegrid_app.deyedevice')),
            ],
        ),
    ]
