# Generated by Django 4.2.28 on 2026-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0032_deyedevice_battery_brand_deyedevice_battery_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyedevice',
            name='financier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
