# Generated by Django 4.2.28 on 2026-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0033_deyedevice_financier'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyedevice',
            name='financier_type',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Owner', 'Owner')], default='Owner', max_length=50),
        ),
    ]
