# Generated by Django 4.2.28 on 2026-03-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0034_deyedevice_financier_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='area',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='deyedevice',
            name='financier_type',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Customer', 'Customer')], default='Customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='deyedevice',
            name='owner',
            field=models.CharField(default='Customer', max_length=100),
        ),
    ]
