# Generated by Django 4.2.28 on 2026-03-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0035_rename_area_teammember_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
