# Generated by Django 4.2.28 on 2026-03-07 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vegrid_app', '0036_teammember_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='region',
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('registration', 'Registration')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='team_docs/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
    ]
