# Generated by Django 4.2.28 on 2026-03-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0037_remove_teammember_region_teammember_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyedevice',
            name='battery_soc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
