# Generated by Django 4.2.28 on 2026-03-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegrid_app', '0038_deyedevice_battery_soc'),
    ]

    operations = [
        migrations.AddField(
            model_name='deyedevice',
            name='station_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
